### ISSUE TITLE
Right hand side bar...

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/Website#1]
Anyone figured how to turn it off yet?

**Comment by SirSparkles** [comment]
The table of contents?

it's set by 
```
toc: true
toc_label: "User Guide"
```
in the 'front matter' for the page in question

See [here](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#table-of-contents) for info

**Comment by Andy-ABTec** [comment]
No, the huge white waste real estate on the right hand side. Had to fix it by editing css in the end.

Strange really, the developer was complaining about being asked how to do it "more times than he could remember".  You'd think if people wanted the space back for content it would be an option in the config somewhere, not a css hack.

**Comment by Andy-ABTec** [comment]
Just out of interest, can you tweak a copy of the program so it picks up this version of the quickstart guide, do a screen grab and post it. I want to see how it scales before I go too much further down "the yellow brick road"...

**Comment by SirSparkles** [comment]
![capture](https://user-images.githubusercontent.com/14905881/35333647-71ac8f40-014a-11e8-9256-15b967e431a9.PNG)

**Comment by SirSparkles** [comment]
Just thinking  - we might be able to do something clever and hide parts of the page if we know it is in the browser. (method would work in either theme)

What I'm thinking is calling quickstart?inapp=true then using javascript from the page to see the header and then hiding parts of the page such as navigation/header

Just an idea at the moment

**Comment by Andy-ABTec** [comment]
Dont think its necessary, the text size seems to be scaling as part of the template design. (try resizing your browser - stuff hides as it needs to) Not sure where the images have gone though, I had them working last night. (they're physically in /assets/images).

**Comment by SirSparkles** [comment]
Re images - not sureif you've seen this post on images: https://mmistakes.github.io/minimal-mistakes/post%20formats/post-image-standard/
