### ISSUE TITLE
uTorrent tab has changed name and now has qBitTorrent support

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/Website#14]

**Comment by Andy-ABTec** [comment]
Updated all the relevant images to "Torrents /NZB" in the tabs and tweaked the Torrents / NZB text to include settings for qBittorrent.

@MarkSummerville please check and let me know if it's ok

**Comment by SirSparkles** [comment]
Looks good - need to update the "The Scan Options Tab" section too though

**Comment by Andy-ABTec** [comment]
Done, missed it the first time round...
