### ISSUE TITLE
Features/Exporting needs to include new ICS export of when to watch

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/Website#18]

**Comment by Andy-ABTec** [comment]
Updated the image - need to tweak the text.

Is this an Apple Calendar? (I'm strictly a Linux/Android/Windows man - the thought of iAnything makes me shudder...)

**Comment by SirSparkles** [comment]
It's a file format supported by most calendar apps: https://en.wikipedia.org/wiki/ICalendar

Not apple related specifically in this case (although iCal was the name of their calendar app a while ago)

**Comment by Andy-ABTec** [comment]
OK, thanks I'll add something to the text

**Comment by Andy-ABTec** [comment]
Done
