### ISSUE TITLE
Web guide for people who have come from other tools

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/Website#20]
Maybe this is just improvements to our getting started guide?

http://ideas.theideawall.com/TVRename/Forum/TopicDetails/4d40ebf9-d4c8-4726-b32d-0ad706ee13eb

Howdy! Great to find TV Rename. 

tl;dr: quick instructions to start using TV Rename for users coming over from TheRenamer. If we can import data fine, otherwise we start anew at TV Rename. Confused also about TV Rename creating .NFO files vs letting Kodi scrape. 

TV Rename looks amazing and robust with WAY too flexible for me to figure out what I need and what I don't. 

Have used therenamer.com for years. It ran wonderfully until theTVDB went to API 2.0. TheRenamer hasn't been updated in 4 years and that is why a lot of us are here. 
Program still works with other databases (imdb, thetvdb, etc). The website is still up. 

Data that is behind therenamer includes support files that have show name and corresponding theTVDB ID Number. There are separate files for each scraper service. Movies, TV, Anime, Fights. Another file independent of scraper force renames the show name - ie: The Late Late Late Show with James Corden. I have it force renamed to James Corden and Kodi picks it up just fine with theTVDB scraper (when the API is working LOL).

**Comment by Andy-ABTec** [comment]
OK, I'll look at expanding the Quickstart guide and including more basic information on the beta site.

Are you looking at expanding the metadata source beyond The TVDB in the near future?

**Comment by Andy-ABTec** [comment]
Added section on fixing usb drive letters in tips and tricks so I can refer to it from the quickstart guide

**Comment by SirSparkles** [comment]
Re TVDB. Then it's the only TVDB for now. It has been a long held idea, so tracked on the idea's wall somewhere, but it's  a lot of work and to be honest until is is something I want to use directly then I doubt it'll happen soon

**Comment by Andy-ABTec** [comment]
Thanks for that, keep an eye on the beta site, you'll see the updates as they happen. I'll update this thread as changes become worth a good look.

**Comment by Andy-ABTec** [comment]
Got up to "3. Run a Scan". just need to rework the last three sections.

So far so good?

**Comment by Andy-ABTec** [comment]
I think that's it!

**Comment by SirSparkles** [comment]
Any way we could make the quick start guide a little more quick?

![image](https://user-images.githubusercontent.com/14905881/44572622-fb7d9d00-a7b6-11e8-94e7-f4faf2d658df.png)

Maybe move some of the early hints about UNC paths etc later in the guide?


![image](https://user-images.githubusercontent.com/14905881/44573014-1bfa2700-a7b8-11e8-9089-102bbc928a68.png)

**Comment by SirSparkles** [comment]
![image](https://user-images.githubusercontent.com/14905881/44573114-624f8600-a7b8-11e8-8f23-99bf71909cae.png)

**Comment by Andy-ABTec** [comment]
Better?

There's not much else you can do without destroying the context...

**Comment by SirSparkles** [comment]
Do you think the pictures add anything?

Hiding the drive information behind the fold is much better. Thanks

**Comment by Andy-ABTec** [comment]
Depending on when you checked, I've now coloured the fold so it looks like a normal link...

I like the second image better though it is possibly a little over-populated. 

It would definitely be useful as an image map if we didn't have the sidebar, with the sidebar I'm not so sure...

**Comment by SirSparkles** [comment]
Fair enough. Thanks again for you timely updates and attention to detail!  Cheers

**Comment by Andy-ABTec** [comment]
Welcome - as ever...
