### ISSUE TITLE
Help>Logs

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/Website#24]
Added new section to "Help and Support" on the beta site - just waiting for correct text and to check functionality.

(I'm guessing that I will need to leave a note to the effect that however the log is viewed the viewer will need closing before returning to TVR proper...)

**Comment by Andy-ABTec** [comment]
Tweaked page content to reflect what's been created so far...

**Comment by Andy-ABTec** [comment]
@MarkSummerville are you done with **Help>Logs**, can I close this?

**Comment by SirSparkles** [comment]
Yeah - not planning anything better on the log front. I have made some 'tweaks' to the settings pages though in the latest RC

**Comment by Andy-ABTec** [comment]
OK thanks, I'll take a look...
