### ISSUE TITLE
Fewer Columns in Scan screen

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/Website#26]
Hey @Andy-ABTec  just so you know. There is now one fewer column in the search results screen. I don't think that it's worth updating all the screenshots, but I've made it a little neater.

Also there is a feature that if the system finds 2 files that might match a missing episode they are now reported against the Missing Episode in the 'error' column

**Comment by Andy-ABTec** [comment]
Thanks, I'll flip back and take a look when I've finished with options...

**Comment by Andy-ABTec** [comment]
Sorry, can't find the "one fewer column"...

**Comment by SirSparkles** [comment]
There used to be two called filename I think:
![image](https://user-images.githubusercontent.com/14905881/47974236-babdd080-e0e3-11e8-95f2-3ea8ee368891.png)


These have been rationalised down to Folder/File/Source

**Comment by Andy-ABTec** [comment]
Thanks for the update, I'll tweak as necessary...

**Comment by Andy-ABTec** [comment]
Fixed...
