### ISSUE TITLE
Update Features/Automation re: upgrade files

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/Website#27]
Logic around the upgrade files function:

1. If we can't tell the length or quality from the file's metadata then we don't do anything (and ask the user)
2. If the present file is longer or better quality we leave it (and remove the new file)
3. if the new file is longer or better quality we replace it
4. if the new file has any of the key terms we use it to replace the existing
5. if the files are identical we do nothing (but remove the new one)
6. If we can't tell then we don't do anything and inform the user (via a new UI element)

**Comment by Andy-ABTec** [comment]
@MarkSummerville before I get too deep into this one...

Does this now happen all the time?
Does it rely on any preferences settings?

Cheers!

**Comment by SirSparkles** [comment]
The whole function is behind a toggle in settings. The % better a file needs to be better is in the settings. The key terms that indicate an improved release are in settings too

**Comment by SirSparkles** [comment]
There is a new screen/dialog too that allows you to select the better file. The bold items show which file is better

**Comment by Andy-ABTec** [comment]
Thanks for the info, I'll go play and document...

**Comment by SirSparkles** [comment]
![image](https://user-images.githubusercontent.com/14905881/48198006-6db35600-e392-11e8-857a-b306b355e743.png)

**Comment by Andy-ABTec** [comment]
Extended Manual>Scan to include the above as it seemed the most logical place to put it...

**Comment by SirSparkles** [comment]
Yeah - I put some copy under Features > Automatic Upgrade too. Prob worth linking together

**Comment by Andy-ABTec** [comment]
Just about done the linking updates but I can't find the target "Notify when new shows are found" referred to in: -

> Further Information
This function can be turned on under Preferences >Scan Options >Notify when new shows are found and the configuration options can be found in Preferences>Bulk/Auto Add. There are options to help modify filenames into show names by ignoring certain terms and by ignoring files altogether with terms in the filename.

**Comment by SirSparkles** [comment]
Looks like a rubbish comment - has been moved to 'Bulk/Auto Add' -> under Auto Add Section

**Comment by Andy-ABTec** [comment]
Fixed...
