### ISSUE TITLE
Document options for New show auto add dialog

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/Website#28]
![image](https://user-images.githubusercontent.com/14905881/48198825-18c50f00-e395-11e8-9e34-ed200e4901d0.png)

Basically that:
 * Skip Auto Add - Stops doing auto add for this scan for all files
 * Ignore File forever - Stops doing auto-add on that file for this (and all future) scans
 * Leave for Later - Ignores this file for this scan
 * Quick Add - Adds selected series to a folder under the selected location
   * NB it uses the defaults for almost all options (timezone etc may be wrong)
   * The locations are based on the ones entered as part of 'Bulk Add'

**Comment by Andy-ABTec** [comment]
Cant get this to appear with my config, what am I missing?

**Comment by SirSparkles** [comment]
Need to: turn on auto add, have a movie file in your download directory and have that file not match something in your library. May need to have some folders in the 'Bulk add' tool specified too

**Comment by Andy-ABTec** [comment]
OK, I'll go play...

**Comment by Andy-ABTec** [comment]
Added new section to the Manual - "Auto Add Shows"
