### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/Website#4]
Do you want the logo in the masthead (Top Left Corner next to "TV Rename")?

**Comment by SirSparkles** [comment]
Yeah - I thought so  - If we can.   My 'feel' is that quite small will suit, but see how you go.

It may be easier to go with the template and put it where this guy's face is: https://mmistakes.github.io/minimal-mistakes/layout-header-image-text-readability/

**Comment by Andy-ABTec** [comment]
It's easier to put it in the masthead.

Afaik the guys head only appears in "blog" style posts, we're using "manual" style posts which have a menu there, otherwise I'll need to reinstate the blank rhs for navigation which seems a waste of space considering the length of the pages.

**Comment by Andy-ABTec** [comment]
Some thing like this?

![image](https://user-images.githubusercontent.com/5175695/35355794-5ebc573e-0146-11e8-88f7-53ac14bf0abb.png)

Maybe just a little bigger, and I still need to play the "home/no horizontal hold" game but you get the idea.

Would give you the site address but it's local only at the moment, having trouble stopping _config.yml syncing up to github. (got a call open with them) I'll let you know when it's fixed. BTW I've put the jquery code on the download button so it always pulls the latest build as well...
