### ISSUE TITLE
Google Analytics failing

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/Website#7]
Have a sneaking feeling this is because the repo is called "website" which automatically sets 

JEKYLL_ENV=development

We need 

JEKYLL_ENV=production

for analytics to work according to the guys over at minimal-mistakes.

Need to clone the site into "gh-pages" and try hosting from there - as far as I can tell this should automatically set "JEKYLL_ENV=production"

**Comment by SirSparkles** [comment]
Sorry, I'm a little confused. The Repo is called "website" and the branch is called "master". I have tried creating another branch called "gh-pages" within the same repo and repointed github pages to "gh-pages"

Let me know whether this helps

**Comment by SirSparkles** [comment]
Do you have any background info?

**Comment by SirSparkles** [comment]
Just fixed it by switching from google to google-universal
